# Generated by Django 5.1.4 on 2025-01-25 17:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='photos/%y/%m/%d')),
                ('product_name', models.CharField(max_length=50, unique=True)),
                ('real_quantity', models.IntegerField(default=0)),
                ('inventory_quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pack_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('party_code', models.AutoField(primary_key=True, serialize=False)),
                ('party_name', models.CharField(max_length=100)),
                ('leader_name', models.CharField(max_length=100)),
                ('wh_leader', models.CharField(max_length=100)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=100)),
                ('state', models.CharField(choices=[('add', 'add'), ('recovery', 'recovery')], default='add', max_length=50)),
                ('party_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lms_app.party')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='photos/%y/%m/%d')),
                ('product_id', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('Dynamic Microphones', 'Dynamic Microphones'), ('Condencer', 'Condencer'), ('Wireless Kit', 'Wireless Kit'), ('Power Cable', 'Power Cable'), ('Electric Cable', 'Electric Cable'), ('A 56 D', 'A 56 D'), ('Signal Cables', 'Signal Cables'), ('Drum Kit', 'Drum Kit'), ('Accessories', 'Accessories'), ('Tools', 'Tools'), ('speaker', 'speaker'), ('mixer', 'mixer'), ('speaker', 'speaker'), ('stands', 'stands'), ('Equipment', 'Equipment'), ('Par light', 'Par light'), ('Dimmer Packs', 'Dimmer Packs')], max_length=50)),
                ('amount_of_parties', models.IntegerField(default=0)),
                ('pack_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lms_app.package')),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lms_app.inventory')),
            ],
        ),
    ]
